// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musical_Instrument_Store.Data;

namespace Musical_Instrument_Store.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210928164408_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Musical_Instrument_Store.Data.Models.MICategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("mICategories");
                });

            modelBuilder.Entity("Musical_Instrument_Store.Data.Models.MusicalInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MICategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("available")
                        .HasColumnType("bit");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("descMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MICategoryId");

                    b.ToTable("MusicalInstruments");
                });

            modelBuilder.Entity("Musical_Instrument_Store.Data.Models.MusicalInstrument", b =>
                {
                    b.HasOne("Musical_Instrument_Store.Data.Models.MICategory", "MICategory")
                        .WithMany("musicalInstruments")
                        .HasForeignKey("MICategoryId");

                    b.Navigation("MICategory");
                });

            modelBuilder.Entity("Musical_Instrument_Store.Data.Models.MICategory", b =>
                {
                    b.Navigation("musicalInstruments");
                });
#pragma warning restore 612, 618
        }
    }
}
